
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pccwassessment@gmail.com
    password: bwvpktgygvhfjyza

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081